### ISSUE TITLE
fatal error: SDL.h: No such file or directory

### ISSUE THREAD

**Issue by FoxieFlakey** [adriancable/8086tiny#10]
What version the 8086tiny need? i have SDL2

When i run 'make' the output is this:

cc 8086tiny.c `sdl-config --cflags --libs` -O3 -fsigned-char -std=c99 -o 8086tiny
/bin/sh: 1: sdl-config: not found
8086tiny.c:18:10: fatal error: SDL.h: No such file or directory
_ 18 | #include "SDL.h"
___ |                ^~~~~~~
compilation terminated.
make: *** [Makefile:16: 8086tiny] Error 1

**Comment by ssieb** [comment]
Did you install the SDL dev package?

**Comment by tkchia** [comment]
Hello @NickWilde263, hello @ssieb,

I believe `8086tiny` requires the SDL1 package.  You should be able to install both SDL1 and SDL2 side by side on the same system.

Thank you!

**Comment by the-loan-wolf** [comment]
you need to install libsdl1.2-dev
On ubuntu type: apt install libsdl1.2-dev

**Comment by FoxieFlakey** [comment]
> you need to install libsdl1.2-dev
> On ubuntu type: apt install libsdl1.2-dev

ok thanks it solved

**Comment by FoxieFlakey** [comment]
how do i close issue in github?

**Comment by raspiduino** [comment]
Just click the close button.

**Comment by FoxieFlakey** [comment]
> Just click the close button.

the `close with comment`?

**Comment by raspiduino** [comment]
> > Just click the close button.
> 
> the `close with comment`?

yeb

**Comment by FoxieFlakey** [comment]
ok found it
